type = "page"
title = "sample1页面"
expand = true
[body]
title = "sample1表单"
type = "form"
mode = "inline"
expand = true
[[body.body]]
type = "input-text" #文本输入框
size = "small"
name = "username"
label = "用户名"
