
title = "示例"
key = '100'
disabled = true
# 表单示例
[[children]]
title = '表单'
key = '1001'

[[children.children]]
title = '基本表单'
key = '10010'
link = "/assets/sample/form.toml"
isLeaf = true
[[children.children]]
title = '表单查询'
key = '10011'
isLeaf = true
