/**
 * Kitty API Doc
 * This is a restful api document of Kitty.
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ForgetPasswordUserDto { 
    code?: string;
    password?: string;
    phoneNumber?: string;
    rePassword?: string;
    type?: number;
}