/**
 * Kitty API Doc
 * This is a restful api document of Kitty.
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MetaField } from './metaField';

export interface MetaObject { 
    bizIntercept?: string;
    config?: string;
    defaultOrder?: string;
    filter?: string;
    groupName?: string;
    isCelledit?: boolean;
    isFirstLoad?: boolean;
    isShowNum?: boolean;
    isSingle?: boolean;
    metaFields?: Array<MetaField>;
    metaId?: number;
    objectCode?: string;
    objectName?: string;
    parentKey?: string;
    pkKey?: string;
    querySql?: string;
    tableName?: string;
}