/**
 * Kitty API Doc
 * This is a restful api document of Kitty.
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SummaryParam } from './summaryParam';

export interface Paging { 
    count?: number;
    rows?: Array<any>;
    summaryParam?: Array<SummaryParam>;
}