/**
 * Kitty API Doc
 * This is a restful api document of Kitty.
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Menu } from './menu';

export interface Role { 
    code?: string;
    id?: number;
    menuList?: Array<Menu>;
    roleName?: string;
    sort?: number;
    status?: number;
}