/**
 * Kitty API Doc
 * This is a restful api document of Kitty.
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Schedule } from './schedule';

export interface StaffScheduleCreateInput { 
    classes?: string;
    creatAt?: Date;
    date?: Date;
    id?: number;
    lastUpdateAt?: Date;
    morningSchedule?: Schedule;
    nightSchedule?: Schedule;
    noonSchedule?: Schedule;
}