/**
 * Kitty API Doc
 * This is a restful api document of Kitty.
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserUpdateDto { 
    abatarUrl?: string;
    email?: string;
    func?: string;
    id?: number;
    nickname?: string;
    phoneNumber?: string;
    rbac?: string;
    roleIdList?: Array<number>;
    sex?: number;
    status?: number;
    userUnit?: string;
    username?: string;
}