/**
 * Kitty API Doc
 * This is a restful api document of Kitty.
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Role } from './role';

export interface User { 
    abatarUrl?: string;
    email?: string;
    func?: string;
    id?: number;
    lastLoginAt?: Date;
    nickname?: string;
    password?: string;
    phoneNumber?: string;
    rbac?: string;
    role?: Role;
    roleId?: number;
    roleList?: Array<Role>;
    sex?: number;
    status?: number;
    userUnit?: string;
    username?: string;
}