export * from './default.service';
import { DefaultService } from './default.service';
export * from './basicErrorController.service';
import { BasicErrorControllerService } from './basicErrorController.service';
export * from './indexController.service';
import { IndexControllerService } from './indexController.service';
export * from './menuController.service';
import { MenuControllerService } from './menuController.service';
export * from './passportController.service';
import { PassportControllerService } from './passportController.service';
export * from './roleController.service';
import { RoleControllerService } from './roleController.service';
export * from './schedulController.service';
import { SchedulControllerService } from './schedulController.service';
export * from './smsController.service';
import { SmsControllerService } from './smsController.service';
export * from './staffController.service';
import { StaffControllerService } from './staffController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [DefaultService, BasicErrorControllerService, IndexControllerService, MenuControllerService, PassportControllerService, RoleControllerService, SchedulControllerService, SmsControllerService, StaffControllerService, UserControllerService];
