/**
 * Kitty API Doc
 * This is a restful api document of Kitty.
 *
 * OpenAPI spec version: 1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */ /* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpEvent } from '@angular/common/http';
import { CustomHttpUrlEncodingCodec } from '../encoder';

import { Observable } from 'rxjs';

import { GetFieldsDto } from '../model/getFieldsDto';
import { MetaObject } from '../model/metaObject';
import { QueryParam } from '../model/queryParam';
import { RtnListMetaObject } from '../model/rtnListMetaObject';
import { RtnMetaObject } from '../model/rtnMetaObject';
import { RtnPaging } from '../model/rtnPaging';
import { Rtnboolean } from '../model/rtnboolean';
import { Rtnobject } from '../model/rtnobject';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';

@Injectable()
export class DefaultService {
  protected basePath = '';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

  /**
   * AddMetaObject
   *
   * @param body meta
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public addMetaObjectUsingPOST(body: MetaObject, observe?: 'body', reportProgress?: boolean): Observable<Rtnboolean>;
  public addMetaObjectUsingPOST(body: MetaObject, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Rtnboolean>>;
  public addMetaObjectUsingPOST(body: MetaObject, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Rtnboolean>>;
  public addMetaObjectUsingPOST(body: MetaObject, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (body === null || body === undefined) {
      throw new Error('Required parameter body was null or undefined when calling addMetaObjectUsingPOST.');
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<Rtnboolean>('post', `${this.basePath}/api/addMetaObject`, {
      body: body,
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }

  /**
   * 实体插入
   *
   * @param body dataItem
   * @param className className
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public dataInsertUsingPOST(
    body: { [key: string]: any },
    className: string,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<Rtnboolean>;
  public dataInsertUsingPOST(
    body: { [key: string]: any },
    className: string,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<Rtnboolean>>;
  public dataInsertUsingPOST(
    body: { [key: string]: any },
    className: string,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<Rtnboolean>>;
  public dataInsertUsingPOST(
    body: { [key: string]: any },
    className: string,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (body === null || body === undefined) {
      throw new Error('Required parameter body was null or undefined when calling dataInsertUsingPOST.');
    }

    if (className === null || className === undefined) {
      throw new Error('Required parameter className was null or undefined when calling dataInsertUsingPOST.');
    }

    let queryParameters = new HttpParams({ encoder: new CustomHttpUrlEncodingCodec() });
    if (className !== undefined && className !== null) {
      queryParameters = queryParameters.set('className', <any>className);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<Rtnboolean>('post', `${this.basePath}/app/stq/entity/insert`, {
      body: body,
      params: queryParameters,
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }

  /**
   * dataUpdate
   *
   * @param body body
   * @param className className
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public dataUpdateUsingPOST(
    body: { [key: string]: any },
    className: string,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<Rtnboolean>;
  public dataUpdateUsingPOST(
    body: { [key: string]: any },
    className: string,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<Rtnboolean>>;
  public dataUpdateUsingPOST(
    body: { [key: string]: any },
    className: string,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<Rtnboolean>>;
  public dataUpdateUsingPOST(
    body: { [key: string]: any },
    className: string,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (body === null || body === undefined) {
      throw new Error('Required parameter body was null or undefined when calling dataUpdateUsingPOST.');
    }

    if (className === null || className === undefined) {
      throw new Error('Required parameter className was null or undefined when calling dataUpdateUsingPOST.');
    }

    let queryParameters = new HttpParams({ encoder: new CustomHttpUrlEncodingCodec() });
    if (className !== undefined && className !== null) {
      queryParameters = queryParameters.set('className', <any>className);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<Rtnboolean>('post', `${this.basePath}/app/stq/entity/update`, {
      body: body,
      params: queryParameters,
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }

  /**
   * detail
   *
   * @param objectCode objectCode
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public detailUsingGET(objectCode?: string, observe?: 'body', reportProgress?: boolean): Observable<RtnMetaObject>;
  public detailUsingGET(objectCode?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RtnMetaObject>>;
  public detailUsingGET(objectCode?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RtnMetaObject>>;
  public detailUsingGET(objectCode?: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    let queryParameters = new HttpParams({ encoder: new CustomHttpUrlEncodingCodec() });
    if (objectCode !== undefined && objectCode !== null) {
      queryParameters = queryParameters.set('objectCode', <any>objectCode);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<RtnMetaObject>('get', `${this.basePath}/api/detail`, {
      params: queryParameters,
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }

  /**
   * entityDelete
   *
   * @param body dataItem
   * @param className className
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public entityDeleteUsingPOST(
    body: { [key: string]: any },
    className?: string,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<Rtnboolean>;
  public entityDeleteUsingPOST(
    body: { [key: string]: any },
    className?: string,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<Rtnboolean>>;
  public entityDeleteUsingPOST(
    body: { [key: string]: any },
    className?: string,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<Rtnboolean>>;
  public entityDeleteUsingPOST(
    body: { [key: string]: any },
    className?: string,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (body === null || body === undefined) {
      throw new Error('Required parameter body was null or undefined when calling entityDeleteUsingPOST.');
    }

    let queryParameters = new HttpParams({ encoder: new CustomHttpUrlEncodingCodec() });
    if (className !== undefined && className !== null) {
      queryParameters = queryParameters.set('className', <any>className);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<Rtnboolean>('post', `${this.basePath}/app/stq/entity/delete`, {
      body: body,
      params: queryParameters,
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }

  /**
   * getFields
   *
   * @param body input
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getFieldsUsingPOST(body: GetFieldsDto, observe?: 'body', reportProgress?: boolean): Observable<Rtnobject>;
  public getFieldsUsingPOST(body: GetFieldsDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Rtnobject>>;
  public getFieldsUsingPOST(body: GetFieldsDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Rtnobject>>;
  public getFieldsUsingPOST(body: GetFieldsDto, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (body === null || body === undefined) {
      throw new Error('Required parameter body was null or undefined when calling getFieldsUsingPOST.');
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<Rtnobject>('post', `${this.basePath}/api/field`, {
      body: body,
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }

  /**
   * GetMetaObjectList
   *
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getMetaObjectListUsingGET(observe?: 'body', reportProgress?: boolean): Observable<RtnListMetaObject>;
  public getMetaObjectListUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RtnListMetaObject>>;
  public getMetaObjectListUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RtnListMetaObject>>;
  public getMetaObjectListUsingGET(observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<RtnListMetaObject>('get', `${this.basePath}/api/list`, {
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }

  /**
   * queryEntity
   *
   * @param body queryParam
   * @param className className
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public queryEntityUsingPOST(body: QueryParam, className: string, observe?: 'body', reportProgress?: boolean): Observable<RtnPaging>;
  public queryEntityUsingPOST(
    body: QueryParam,
    className: string,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<RtnPaging>>;
  public queryEntityUsingPOST(
    body: QueryParam,
    className: string,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<RtnPaging>>;
  public queryEntityUsingPOST(
    body: QueryParam,
    className: string,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (body === null || body === undefined) {
      throw new Error('Required parameter body was null or undefined when calling queryEntityUsingPOST.');
    }

    if (className === null || className === undefined) {
      throw new Error('Required parameter className was null or undefined when calling queryEntityUsingPOST.');
    }

    let queryParameters = new HttpParams({ encoder: new CustomHttpUrlEncodingCodec() });
    if (className !== undefined && className !== null) {
      queryParameters = queryParameters.set('className', <any>className);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<RtnPaging>('post', `${this.basePath}/app/stq/query`, {
      body: body,
      params: queryParameters,
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }
}
