/**
 * Kitty API Doc
 * This is a restful api document of Kitty.
 *
 * OpenAPI spec version: 1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */ /* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpEvent } from '@angular/common/http';
import { CustomHttpUrlEncodingCodec } from '../encoder';

import { Observable } from 'rxjs';

import { Rtnboolean } from '../model/rtnboolean';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';

@Injectable()
export class MenuControllerService {
  protected basePath = '';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

  /**
   * deleteById
   *
   * @param id id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public deleteByIdUsingDELETE(id?: number, observe?: 'body', reportProgress?: boolean): Observable<Rtnboolean>;
  public deleteByIdUsingDELETE(id?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Rtnboolean>>;
  public deleteByIdUsingDELETE(id?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Rtnboolean>>;
  public deleteByIdUsingDELETE(id?: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    let queryParameters = new HttpParams({ encoder: new CustomHttpUrlEncodingCodec() });
    if (id !== undefined && id !== null) {
      queryParameters = queryParameters.set('id', <any>id);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<Rtnboolean>('delete', `${this.basePath}/api/menu/deleteById`, {
      params: queryParameters,
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }

  /**
   * menuAdd
   *
   * @param icon
   * @param id
   * @param link
   * @param name
   * @param parentId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public menuAddUsingPOST(
    icon?: string,
    id?: number,
    link?: string,
    name?: string,
    parentId?: string,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<Rtnboolean>;
  public menuAddUsingPOST(
    icon?: string,
    id?: number,
    link?: string,
    name?: string,
    parentId?: string,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<Rtnboolean>>;
  public menuAddUsingPOST(
    icon?: string,
    id?: number,
    link?: string,
    name?: string,
    parentId?: string,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<Rtnboolean>>;
  public menuAddUsingPOST(
    icon?: string,
    id?: number,
    link?: string,
    name?: string,
    parentId?: string,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let queryParameters = new HttpParams({ encoder: new CustomHttpUrlEncodingCodec() });
    if (icon !== undefined && icon !== null) {
      queryParameters = queryParameters.set('icon', <any>icon);
    }
    if (id !== undefined && id !== null) {
      queryParameters = queryParameters.set('id', <any>id);
    }
    if (link !== undefined && link !== null) {
      queryParameters = queryParameters.set('link', <any>link);
    }
    if (name !== undefined && name !== null) {
      queryParameters = queryParameters.set('name', <any>name);
    }
    if (parentId !== undefined && parentId !== null) {
      queryParameters = queryParameters.set('parentId', <any>parentId);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<Rtnboolean>('post', `${this.basePath}/api/menu/menuAdd`, {
      params: queryParameters,
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }

  /**
   * menuQuery
   *
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public menuQueryUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Rtnboolean>;
  public menuQueryUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Rtnboolean>>;
  public menuQueryUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Rtnboolean>>;
  public menuQueryUsingGET(observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<Rtnboolean>('get', `${this.basePath}/api/menu/menuQuery`, {
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }

  /**
   * menuUpdate
   *
   * @param icon
   * @param id
   * @param link
   * @param name
   * @param parentId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public menuUpdateUsingPOST(
    icon?: string,
    id?: number,
    link?: string,
    name?: string,
    parentId?: string,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<Rtnboolean>;
  public menuUpdateUsingPOST(
    icon?: string,
    id?: number,
    link?: string,
    name?: string,
    parentId?: string,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<Rtnboolean>>;
  public menuUpdateUsingPOST(
    icon?: string,
    id?: number,
    link?: string,
    name?: string,
    parentId?: string,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<Rtnboolean>>;
  public menuUpdateUsingPOST(
    icon?: string,
    id?: number,
    link?: string,
    name?: string,
    parentId?: string,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let queryParameters = new HttpParams({ encoder: new CustomHttpUrlEncodingCodec() });
    if (icon !== undefined && icon !== null) {
      queryParameters = queryParameters.set('icon', <any>icon);
    }
    if (id !== undefined && id !== null) {
      queryParameters = queryParameters.set('id', <any>id);
    }
    if (link !== undefined && link !== null) {
      queryParameters = queryParameters.set('link', <any>link);
    }
    if (name !== undefined && name !== null) {
      queryParameters = queryParameters.set('name', <any>name);
    }
    if (parentId !== undefined && parentId !== null) {
      queryParameters = queryParameters.set('parentId', <any>parentId);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<Rtnboolean>('post', `${this.basePath}/api/menu/menuUpdate`, {
      params: queryParameters,
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }
}
