/**
 * Kitty API Doc
 * This is a restful api document of Kitty.
 *
 * OpenAPI spec version: 1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */ /* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpEvent } from '@angular/common/http';
import { CustomHttpUrlEncodingCodec } from '../encoder';

import { Observable } from 'rxjs';

import { RoleUpdateDto } from '../model/roleUpdateDto';
import { RtnRole } from '../model/rtnRole';
import { Rtnboolean } from '../model/rtnboolean';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';

@Injectable()
export class RoleControllerService {
  protected basePath = '';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

  /**
   * deleteById
   *
   * @param id id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public deleteByIdUsingDELETE2(id?: number, observe?: 'body', reportProgress?: boolean): Observable<Rtnboolean>;
  public deleteByIdUsingDELETE2(id?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Rtnboolean>>;
  public deleteByIdUsingDELETE2(id?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Rtnboolean>>;
  public deleteByIdUsingDELETE2(id?: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    let queryParameters = new HttpParams({ encoder: new CustomHttpUrlEncodingCodec() });
    if (id !== undefined && id !== null) {
      queryParameters = queryParameters.set('id', <any>id);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<Rtnboolean>('delete', `${this.basePath}/api/role/deleteById`, {
      params: queryParameters,
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }

  /**
   * detailById
   *
   * @param id Id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public detailByIdUsingGET(id?: number, observe?: 'body', reportProgress?: boolean): Observable<RtnRole>;
  public detailByIdUsingGET(id?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RtnRole>>;
  public detailByIdUsingGET(id?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RtnRole>>;
  public detailByIdUsingGET(id?: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    let queryParameters = new HttpParams({ encoder: new CustomHttpUrlEncodingCodec() });
    if (id !== undefined && id !== null) {
      queryParameters = queryParameters.set('Id', <any>id);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<RtnRole>('get', `${this.basePath}/api/role/detail/${encodeURIComponent(String(id))}`, {
      params: queryParameters,
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }

  /**
   * roleAdd
   *
   * @param code
   * @param menuIdList
   * @param roleName
   * @param sort
   * @param status
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public roleAddUsingPOST(
    code?: string,
    menuIdList?: Array<number>,
    roleName?: string,
    sort?: number,
    status?: number,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<Rtnboolean>;
  public roleAddUsingPOST(
    code?: string,
    menuIdList?: Array<number>,
    roleName?: string,
    sort?: number,
    status?: number,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<Rtnboolean>>;
  public roleAddUsingPOST(
    code?: string,
    menuIdList?: Array<number>,
    roleName?: string,
    sort?: number,
    status?: number,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<Rtnboolean>>;
  public roleAddUsingPOST(
    code?: string,
    menuIdList?: Array<number>,
    roleName?: string,
    sort?: number,
    status?: number,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let queryParameters = new HttpParams({ encoder: new CustomHttpUrlEncodingCodec() });
    if (code !== undefined && code !== null) {
      queryParameters = queryParameters.set('code', <any>code);
    }
    if (menuIdList) {
      menuIdList.forEach(element => {
        queryParameters = queryParameters.append('menuIdList', <any>element);
      });
    }
    if (roleName !== undefined && roleName !== null) {
      queryParameters = queryParameters.set('roleName', <any>roleName);
    }
    if (sort !== undefined && sort !== null) {
      queryParameters = queryParameters.set('sort', <any>sort);
    }
    if (status !== undefined && status !== null) {
      queryParameters = queryParameters.set('status', <any>status);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<Rtnboolean>('post', `${this.basePath}/api/role/roleAdd`, {
      params: queryParameters,
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }

  /**
   * roleQuery
   *
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public roleQueryUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Rtnboolean>;
  public roleQueryUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Rtnboolean>>;
  public roleQueryUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Rtnboolean>>;
  public roleQueryUsingGET(observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<Rtnboolean>('get', `${this.basePath}/api/role/roleQuery`, {
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }

  /**
   * roleUpdate
   *
   * @param body roleUpdateDto
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public roleUpdateUsingPOST(body: RoleUpdateDto, observe?: 'body', reportProgress?: boolean): Observable<Rtnboolean>;
  public roleUpdateUsingPOST(body: RoleUpdateDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Rtnboolean>>;
  public roleUpdateUsingPOST(body: RoleUpdateDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Rtnboolean>>;
  public roleUpdateUsingPOST(body: RoleUpdateDto, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (body === null || body === undefined) {
      throw new Error('Required parameter body was null or undefined when calling roleUpdateUsingPOST.');
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<Rtnboolean>('post', `${this.basePath}/api/role/roleUpdate`, {
      body: body,
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }
}
