type = "page"
[body]
type = "form"
[[body.body]]
type = "input-number"
label = "数量"
name = "number"
value = 0
description = "调整数量大小查看效果吧！"
[[body.body]]
type = "input-text"
label = "文本"
name = "text"
disabledOn = "this.number > 1"
description = "当数量大于1的时候，该文本框会被禁用"
