[[templates]]
name = "meta-form"
type = "html"
path = "form.component.html"
[[templates]]
name = "meta-form"
type = "ts"
path = "form.component.ts"
[[templates]]
name = "meta-form"
type = "css"
path = "form.component.css"
